// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjcvhtrmspvubyrwfnak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qY3ZodHJtc3B2dWJ5cndmbmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyMDU4MDAsImV4cCI6MjA5Mzc4MTgwMH0.yqM5u7WXt_NjUlb5fqjhpJA7q0etZvQut46rX4ZXtTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});